### ISSUE TITLE
Update to Blazor 0.5.0 (0.7.0 now)

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorDB#13]

**Comment by william-kid** [comment]
We are up to  0.7.0 now

**Comment by chanan** [comment]
Yes, sorry been lagging behind because the update to 0.5.0 messed up the javascript with the async calls. I think its fixable now (since 0.6.0) with the async handler that were added.

I will try to update 0.7.0 this weekend. Sorry for the delay.

**Comment by william-kid** [comment]
No worries.  It's all experimental and we are still on 0.5.0 for development due to other libraries still working on support for 0.6.0.

**Comment by chanan** [comment]
Ran into the same problem with 0.7.0 but managed to narrow it down this time. Although the error makes no sense to me yet, It's an Null pointer writing via javascript to the console. Still working on this.,

Narrowed down the location of the error but it makes no sense to me yet. It is getting a NPE trying to write to the console from JS. Not sure why this should start happening. I will keep working on this, but I think I will need to open an issue on the Blazor project.

**Comment by chanan** [comment]
Took a while to figure out where the issue is, but it seems like I am getting null from JSRuntime.Current. Not sure how to reproduce outside of BlazorDB, asked on the Glitter channel. If I dont get an answer, I will try to figure out how to reproduce in a small sample and enter a ticket in the aspnet github repository.

**Comment by chanan** [comment]
Entered a ticket in the Blazor Repo: https://github.com/aspnet/Blazor/issues/1746

**Comment by chanan** [comment]
Finally closed!

Please note the breaking change list in main readme
